# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomTabBarController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomTabBarController
	pod 'Material', '3.1.8'
	pod 'IQKeyboardManagerSwift', '6.3.0'
	pod 'RealmSwift', '10.24.1'
	pod 'R.swift'
	pod 'Moya', '14.0'
	pod 'Alamofire', '5.7.1'
	pod 'RxSwift', '5.1.1'
  	pod 'RxCocoa', '5.1.1'
	pod 'SwiftyJSON', '5.0.1'
	pod 'Toast-Swift', '5.0.1'
	pod 'PromiseKit', '6.17.0'
	pod 'Kingfisher'

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
               end
          end
   end
end